version: "3.8"
services:
  mongodb:
    image: mongo:7
    ports:
      - "27017:27017"
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: papers
    ports:
      - "5432:5432"
  backend:
    build: ../backend
    depends_on:
      - mongodb
      - qdrant
      - postgres
    environment:
      POSTGRES_URL: postgresql://postgres:postgres@postgres:5432/papers
  # typesense:
  #   image: typesense/typesense:latest
  #   environment:
  #     - TYPESENSE_API_KEY=xyz
  #   ports:
  #     - '8108:8108'
