version: '3.8'
services:
  mongodb:
    image: mongo:7
    ports:
      - '27017:27017'
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - '6333:6333'
      - '6334:6334'
  backend:
    build: ../backend
    depends_on:
      - mongodb
      - qdrant
  # typesense:
  #   image: typesense/typesense:latest
  #   environment:
  #     - TYPESENSE_API_KEY=xyz
  #   ports:
  #     - '8108:8108'
