name: CI
on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.12"]
        node: ["20"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: Run setup
        run: ./.codex/setup.sh
      - name: Build frontend
        run: pnpm --prefix frontend build
      - name: Deploy
        run: echo "deploy placeholder"
